묶음배송 및 상품등록 api를 추가했습니다!
rimo030/nestjs-e-commerce-frame pull request #54
Opened 2023-11-20 22:03 UTC by rimo030

## Background(배경지식)
#52 코멘트 내용을 반영하고 묶음배송 및 상품등록 api를 추가했습니다!

## Implementations(보충설명)
- 판매자(seller)는 상품을 등록할 수 있다.
- 판매자는 묶음 배송 그룹을 등록 할 수 있다.

위의 요구사항을 반영하였습니다.

2023-11-21 01:31 UTC, kakasoo requested changes
JWT 인증이 구매자와 판매자가 별도인 걸 증명해주세요.
토큰에 id 외에 { role: 'seller' } 라는 식으로 넣어둬도 좋습니다만, 이게 조작 가능성이 있으므로 보안 인증 용으로 쓰면 안됩니다.

2023-11-21 01:31 UTC, kakasoo commented on docker-compose.yml
> +    container_name: CommerceDB
드디어 바꿨군요. LGTM.

2023-11-21 01:31 UTC, kakasoo commented on src/auth/auth.controller.ts
>    }
NestJS 데코레이터 중에 statusCode 라는 데코레이터가 있습니다. 이 엔드포인트 위에 statusCode(201)이라고 작성해주세요. statusCode의 종류에 대해서는 말씀드린 적 있습니다.

2023-11-21 01:31 UTC, kakasoo commented on src/auth/auth.controller.ts
> +    return this.authService.sellrLogin(sellerId);
아마도 토큰을 리턴할 것 같은데요, 모든 응답은 반드시 객체 형태가 되게 해주세요.
테스트 코드에 임시로 만든 코드가 있을 겁니다. 저라면 data, 성공 여부를 의미하는 result, 구체적인 상태를 의미하는 2xxx의 상태 코드를 넣을 겁니다.
상태 코드를 넣는 건 200, 201, 204 등 백의 자리로는 서비스를 모두 표현하는 게 불가능하기 때문입니다.

여담으로 구글과 메타는 만의 자리 이상이 나오더라고요.

2023-11-21 01:31 UTC, kakasoo commented on src/auth/auth.controller.ts
>    }
작성하다 만 엔드포인트에 대해서는 JSDoc으로 주석을 써서, @ 기호에 todo를 써주세요. 앞으로 무얼 작성할지 적어두면 다른 개발자가 이어서 개발하기가 편할 겁니다.

2023-11-21 01:31 UTC, kakasoo commented on src/auth/auth.service.ts
> +import { Payload } from 'src/interfaces/payload';
지금은 모든 형태가 동일해서 Payload로 충분하지만, 만약 Role에 따라 Payload가 달라지는 상황이 되면 다 나눠서 정의해야 한다는 것, 이미 아시죠?
LGTM.

2023-11-21 01:31 UTC, kakasoo commented on src/auth/auth.service.ts
>      @InjectRepository(BuyersRespository)
이게 없어도 동작한다면 제거해주셔도 됩니다.

2023-11-21 01:31 UTC, kakasoo commented on src/auth/auth.service.ts
>    }
혹시나 해서 테스트 코드 작성을 요구드립니다. 지금 인증에서 구매자, 판매자가 혹시 동일한 JWT 전략과 secret을 사용하고 있다면 구매자 토큰으로 판매자 API 호출이 가능한 괴랄한 일이 벌어질 거 같은데요, 테스트 코드를 짜고 그렇지 않다는 걸 증명해주세요.

**이걸 증명 못하면 이 PR은 merge 못합니다.**

2023-11-21 01:31 UTC, kakasoo commented on src/auth/user.decorator.ts
굳이 User 데코레이터를 없앨 필요까진 없었지만, 사용하지 않으신다면 지우셔도 좋습니다.

2023-11-21 01:31 UTC, kakasoo commented on src/configs/typeorm.config.ts
> +  database: 'commerce',
잊지 않고 잘 바꿔주셨습니다.

2023-11-21 01:31 UTC, kakasoo commented on src/configs/typeorm.config.ts
>    synchronize: true,
이 부분은 process.env.NODE_ENV를 검사해서 오직 local에서만 돌아가게 해주세요. 프로덕션이나 개발 서버에서 동작해선 절대 안됩니다.

2023-11-21 01:31 UTC, kakasoo commented on src/controllers/sellers.controller.ts
> +    await this.sellerservice.createProduct(createProductDto);
여기도 sellerId를 전달해야할 필요성이 보입니다.

2023-11-21 01:31 UTC, kakasoo commented on src/entities/dtos/create-product-bundle.dto.ts
> +}
배송비 기준이 유료일 때 배송비는 얼마인가?
묶음 배송에 대한 단일 배송비를 의미하는 값과,
배송비 기준을 충족하지 못했다는 기준 값이 없습니다. 예를 들어 30,000원 이상 구매 시 무료라면 30,000원이라는 프로퍼티가 있었겠죠?

2023-11-21 01:31 UTC, kakasoo commented on src/entities/dtos/create-product-bundle.dto.ts
> +export class CreateProductBundleDto {
PickType을 사용하지 않은 것은 아무래도 좋지만, implements Pick<ProductBundleEntity, 'bundleName' | 'feeStandard'> 구문을 써주세요.
추가로 조건부로 필요한 칼럼은 Partial 타입으로 감싸면 됩니다.

2023-11-21 01:31 UTC, kakasoo commented on src/entities/dtos/create-product-bundle.dto.ts
> +export class CreateProductBundleDto {
이렇게 타입을 지정하면 내부 타입이 똑같지 않으면 타입 에러를 뱉어주기 때문에 더 안전할 거고, 자동완성 기능으로 DTO를 빠르게 완성할 수 있습니다.

2023-11-21 01:31 UTC, kakasoo commented on src/types/enums/fee-standard.enum.ts
> +}
굿입니다.

2023-11-21 01:31 UTC, kakasoo commented on src/types/enums/fee-type.enum.ts
> +}
실제 용어가 있는지 알아보면 좋겠어요. 제가 대충 지은 단어들 말고요. :)

2023-11-22 13:55 UTC, rimo030 commented
구매자(buyer)와 판매자(seller)의 JWT secret을 분리하였습니다.
이제 같은 id를 가지는 buyer와 seller의 별개의 인증이 가능해졌습니다!

2023-11-23 01:22 UTC, kakasoo commented
LGTM

2023-11-23 10:54 UTC, merged